/*
MIT License

Copyright (c) 2022 Slai

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	beamrunnerv1 "github.com/slai-labs/beamcrds/pkg/beamrunner/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBeamRunners implements BeamRunnerInterface
type FakeBeamRunners struct {
	Fake *FakeWorkV1
	ns   string
}

var beamrunnersResource = schema.GroupVersionResource{Group: "work.slai.io", Version: "v1", Resource: "beamrunners"}

var beamrunnersKind = schema.GroupVersionKind{Group: "work.slai.io", Version: "v1", Kind: "BeamRunner"}

// Get takes name of the beamRunner, and returns the corresponding beamRunner object, and an error if there is any.
func (c *FakeBeamRunners) Get(ctx context.Context, name string, options v1.GetOptions) (result *beamrunnerv1.BeamRunner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(beamrunnersResource, c.ns, name), &beamrunnerv1.BeamRunner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beamrunnerv1.BeamRunner), err
}

// List takes label and field selectors, and returns the list of BeamRunners that match those selectors.
func (c *FakeBeamRunners) List(ctx context.Context, opts v1.ListOptions) (result *beamrunnerv1.BeamRunnerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(beamrunnersResource, beamrunnersKind, c.ns, opts), &beamrunnerv1.BeamRunnerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &beamrunnerv1.BeamRunnerList{ListMeta: obj.(*beamrunnerv1.BeamRunnerList).ListMeta}
	for _, item := range obj.(*beamrunnerv1.BeamRunnerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested beamRunners.
func (c *FakeBeamRunners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(beamrunnersResource, c.ns, opts))

}

// Create takes the representation of a beamRunner and creates it.  Returns the server's representation of the beamRunner, and an error, if there is any.
func (c *FakeBeamRunners) Create(ctx context.Context, beamRunner *beamrunnerv1.BeamRunner, opts v1.CreateOptions) (result *beamrunnerv1.BeamRunner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(beamrunnersResource, c.ns, beamRunner), &beamrunnerv1.BeamRunner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beamrunnerv1.BeamRunner), err
}

// Update takes the representation of a beamRunner and updates it. Returns the server's representation of the beamRunner, and an error, if there is any.
func (c *FakeBeamRunners) Update(ctx context.Context, beamRunner *beamrunnerv1.BeamRunner, opts v1.UpdateOptions) (result *beamrunnerv1.BeamRunner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(beamrunnersResource, c.ns, beamRunner), &beamrunnerv1.BeamRunner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beamrunnerv1.BeamRunner), err
}

// Delete takes name of the beamRunner and deletes it. Returns an error if one occurs.
func (c *FakeBeamRunners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(beamrunnersResource, c.ns, name, opts), &beamrunnerv1.BeamRunner{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBeamRunners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(beamrunnersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &beamrunnerv1.BeamRunnerList{})
	return err
}

// Patch applies the patch and returns the patched beamRunner.
func (c *FakeBeamRunners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *beamrunnerv1.BeamRunner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(beamrunnersResource, c.ns, name, pt, data, subresources...), &beamrunnerv1.BeamRunner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beamrunnerv1.BeamRunner), err
}
